from functions.run_python_file import run_python_file

# print("running test 1")
print(run_python_file("calculator", "main.py"))
# print("running test 2")
print(run_python_file("calculator", "main.py", ["3 + 5"]))
# print("running test 3")
print(run_python_file("calculator", "tests.py"))
# print("running test 4")
print(run_python_file("calculator", "../main.py"))
# print("running test 5")
print(run_python_file("calculator", "nonexistent.py"))
# print("running test 6")
print(run_python_file("calculator", "lorem.txt"))
# print("end")